### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by Moerfiane** [fredhodgman/liftoff#5]
- [x] I can request from the user Username
- [x] I can request from the user Email.
- [x] I can request from the user First Name.
- [x] I can request from the user Last Name.
- [x] I can request from the user Password.
- [x] Then write the inforation to the database.

**Comment by Moerfiane** [comment]
New User:

As a developer I need to be able to to know what information is required to obtain an account. I need to know what is required or what can optionaly be left blank.

Accepted when:
I can request from the user Username.
I can request from the user Email.
I can request from the user First Name.
I can request from the user Last Name. 
I can request from the user Password.
Then write the inforation to the database.
